import { NgModule } from '@angular/core';

import {
    MatCardModule,
    MatStepperModule,
    MatTabsModule,
    MatRippleModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatNativeDateModule,
    MatTreeModule,
    MatBadgeModule,
    MatButtonModule,
    MatDividerModule,
    MAT_DATE_LOCALE,
    MatBottomSheetModule,
    MatInputModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatRadioModule,
    MatSelectModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSidenavModule,
    MatToolbarModule,
    MatGridListModule,
    MatCheckboxModule,
    MatListModule
} from '@angular/material';

@NgModule({
    providers: [
        {provide: MAT_DATE_LOCALE, useValue: 'sr_Cyrl'}
    ],
    exports: [
        MatCardModule,
    MatStepperModule,
    MatTabsModule,
    MatRippleModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatNativeDateModule,
    MatTreeModule,
    MatBadgeModule,
    MatButtonModule,
    MatDividerModule,
    MatBottomSheetModule,
    MatInputModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatRadioModule,
    MatSelectModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSidenavModule,
    MatToolbarModule,
    MatGridListModule,
    MatCheckboxModule,
    MatListModule
    ]
})
export class SharedMaterialModule { }